### PR TITLE
Deploy after retro 08/04/2017 - Update master with new gzip rules

### PR DESCRIPTION
**Pull request by jseppi**

### CODE REVIEW

**Comment by jmhooper** [comment]
Is there a reason we want to do this now instead of after retro?

**Comment by jseppi** [comment]
Nope, no urgency. Just setting it up. It doesn't auto-deploy anyway though.

**Comment by jmhooper** [comment]
Reminder to merge this after retro

**Comment by jseppi** [comment]
deployed!

**Pull request merged**
