### PR TITLE
Handle "redirect" object paths

### PR DESCRIPTION
**Pull request by davemcorwin**
Addresses #113 

## Changes proposed in this pull request:
Handles potential "redirect" objects created by the garden build by first assuming that any `/foo` path will result in a redirect object to `/foo/index.html`. If this doesn't exist, then `/foo` will be attempted and the 404 will be returned if it doesn't exist.

Note: this does include an update to the local/test environment to openresty, which is not technically required now, but will be in the future if we need to jump into lua.

## security considerations
None

### CODE REVIEW

**Comment by svenaas** [comment]
Tests are failing locally for me as well.

**Comment by davemcorwin** [comment]
Commented out Ben's changes that seemed to be causing intermittent test failures. Will investigate after this PR.

**Comment by svenaas** [comment]
I still have 40 tests failing and 5 passing from both 
`docker-compose run --rm app npm test`
and
`docker-compose run --rm app npm run test:integration`

The problem may be with my methodology, not the code. I have tried on VPN, just in case. I have tried rolling back with `rm -rf node_modules && npm i` and then `docker-compose run --no-deps --rm app npm install`. I have run the relevant `parse` task before each test run. Possible signs of trouble: 

1. These warnings:
> WARN[0000] The "SHARED_AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DEDICATED_AWS_ACCESS_KEY_ID" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "DEDICATED_AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "SHARED_AWS_SECRET_ACCESS_KEY" variable is not set. Defaulting to a blank string.
2. The fact that both test tasks seem to run the same set of tests.

**Comment by davemcorwin** [comment]
That's because you are missing the required environment variables...i'll push up some docs

**Comment by svenaas** [comment]
Works for me now.

**Review by svenaas — APPROVED** [review]

**Comment by svenaas** [comment]
With Ben's changes back: 

The _first_ time I ran the integration tests I got
```
  44 passing (37s)
  1 failing

  1) For `federalist-proxy-staging` hosts
       returns results from the SHARED bucket:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/test/main.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

The _second_ time I ran the integration tests I got
```
  44 passing (36s)
  1 failing

  1) For `federalist-proxy-staging` hosts
       returns results from the SHARED bucket:
     Error: expected 200 "OK", got 404 "Not Found"
      at Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.assert (node_modules/supertest/lib/test.js:173:18)
      at localAssert (node_modules/supertest/lib/test.js:131:12)
      at /app/node_modules/supertest/lib/test.js:128:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:728:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:916:18)
      at IncomingMessage.emit (domain.js:475:12)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

The _third_ time I ran the integration tests I got 
```
  45 passing (37s)
```

**Comment by svenaas** [comment]
@davemcorwin I was testing this. Note results above ⬆️

**Comment by svenaas** [comment]
The regular tests against mock ran successfully all five times I tried them.

**Pull request merged**
