### PR TITLE
set redirect path based on user agent header

### PR DESCRIPTION
**Pull request by davemcorwin**
## Changes proposed in this pull request:
- redirects based on user agent header (if Amazon Cloudfront)
- #121 

## security considerations
None -  but it is a string comparison and redirects are relative only

### CODE REVIEW

**Comment by davemcorwin** [comment]
nginx continues to blow my mind

**Review by svenaas — APPROVED** [review]
This looks like it falls solidly in the "we're going to have to try it on staging" category.

**Comment by davemcorwin** [comment]
I already did ;)

**Comment by svenaas** [comment]
Oh I'm sorry were those exactly the same regexes as before? I am positively _abashed_ not to have recognized them. 😛

**Pull request merged**
