### PR TITLE
Release 2022-01-05 | E2E encryption

### PR DESCRIPTION
**Pull request by davemcorwin**
## Changes proposed in this pull request:
- Support for https access to S3 buckets sans website config
- Integration tests and more thorough test suite
- Upgrade to OpenResty
- Restore staging deployments to Circle CI
- Readme and CI updates

## security considerations
None

### CODE REVIEW

**Review by svenaas — APPROVED** [review]
This is **a lot**. 

I believe the PR template and security considerations workflow are just along for the ride here, correct? 

Anyway I have looked this over to the best of my abilities and I don't see anything that is setting off alarms for me. I think the most important test of this one is going to be running it in the staging environment, so let's do that.

**Comment by davemcorwin** [comment]
This is currently running in staging, the PR would deploy it to production.

**Comment by svenaas** [comment]
Indeed. I thought this was additional work, not the summation of the work. It's more overwhelming all at once.

Here's a question: do you have any idea why CircleCI is stalled?

Also: it looks like main changed out from under this at some point; you might want to update this branch and let the tests run again.

**Comment by davemcorwin** [comment]
Circle appears "stalled" because the name of the job changed in the configuration, `build-test-deploy` ran fine, but `ci/circleci: build-and-test ` was never run. I will update the branch protections to reflect this.

**Comment by svenaas** [comment]
Looks much happier now.

**Pull request merged**
