### PR TITLE
Add text/html type for cfm extension

### PR DESCRIPTION
**Pull request by jseppi**
ref https://github.com/18F/federalist-proxy/issues/19

### CODE REVIEW

**Comment by jseppi** [comment]
Not 100% sure of this change yet. I don't know if redefining the `types` block is additive, or if it will totally replace the types mapping that is already imported from https://github.com/18F/federalist-proxy/blob/023f2be3c1f8b5b39b5795b08690530a1ebed4b0/nginx.conf#L12

**Comment by jseppi** [comment]
According to https://stackoverflow.com/questions/16789494/extending-default-nginx-mime-types-file/20566966#20566966 and [discussion in slack](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1510185695000189), this should be good now.

**Comment by wslack** [comment]
How do we test?

**Comment by wslack** [comment]
(Should we have a staging proxy?)

**Comment by jseppi** [comment]
We do have a staging proxy, and it has been deployed. We can have plainlanguage.gov do a build there to test out their specific case. Once federalist-staging is back up, that is.

**Pull request merged**
